spring:
  application:
    name: call-your-mechanic
  datasource:
    url: jdbc:postgresql://localhost:5432/call-your-mechanic
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  devtools:
    add-properties: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true


app:
  auth:
    otp-expiry-seconds: 300
    otp-resend-cooldown-seconds: 60
    otp-max-attempts: 5

# SMS provider
sms:
  accountSid: AC50039e27063e1d32436f92a8d04f3780
  authToken:  62bffff16d7beb369fe7d21cba88c715
  fromNumber: +1 507 776 5377


security:
  jwt:
    secret: e0S8JplmeKf5Sq8hJrPdpc3VbH1wVlAbAzzVjlsdhNr
    access-token-ttl: PT15M
    refresh-token-ttl: P30D
