spring:
  application:
    name: call-your-mechanic
  datasource:
    url: jdbc:postgresql://localhost:5432/call-your-mechanic
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  devtools:
    add-properties: false

app:
  auth:
    otp-expiry-seconds: 300
    otp-resend-cooldown-seconds: 60
    otp-max-attempts: 5

# SMS provider
accountSid: AC50039e27063e1d32436f92a8d04f3780
authToken:  62bffff16d7beb369fe7d21cba88c715
fromNumber: +1 507 776 5377
