spring:
  cache:
    type: simple
  sql:
    init:
      mode: always
  jpa:
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

app:
  auth:
    mock-sms-enabled: true
    fixed-otp: 123456
