spring:
  application:
    name: call-your-mechanic
  datasource:
    url: jdbc:postgresql://localhost:5432/call-your-mechanic
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  devtools:
    add-properties: false

app:
  auth:
    otp-expiry-seconds: 300
    otp-resend-cooldown-seconds: 60
    otp-max-attempts: 5
